# dict = b"{'YfO28Ihehbk': {'id': 'YfO28Ihehbk', 'chnlid': 'UC59K-uG2A5ogwIrHw4bmlEg', 'categ_id': 28, 'title': 'Python Tutorial for Beginner | Full Course', 'view_count': '593691', 'likecount': '13067', 'dislikecount': '184', 'lang': 'en'}, 'OTmQOjsl0eg': {'id': 'OTmQOjsl0eg', 'chnlid': 'UC59K-uG2A5ogwIrHw4bmlEg', 'categ_id': 28, 'title': 'Django Tutorial for Beginners | Full Course', 'view_count': '873252', 'likecount': '13386', 'dislikecount': '373', 'lang': 'en'}, 'F5mRW0jo-U4': {'id': 'F5mRW0jo-U4', 'chnlid': 'UC8butISFwT-Wl7EV0hUK0BQ', 'categ_id': 27, 'title': 'Python Django Web Framework - Full Course for Beginners', 'view_count': '1796691', 'likecount': '24907', 'dislikecount': '614', 'lang': 'en'}, 'JT80XhYJdBw': {'id': 'JT80XhYJdBw', 'chnlid': 'UCqrILQNl5Ed9Dz6CGMyvMTQ', 'categ_id': 27, 'title': 'Python Django Tutorial 2020 - Full Course for Beginners', 'view_count': '670327', 'likecount': '19565', 'dislikecount': '704', 'lang': 'en'}, 'HRLIEgwYSHc': {'id': 'HRLIEgwYSHc', 'chnlid': 'UCkw4JCwteGrDHIsyIIKo4tQ', 'categ_id': 27, 'title': 'Python Django Tutorial | Learn Python Django In 3 Hours | Python Web Development | Edureka', 'view_count': '148862', 'likecount': '2215', 'dislikecount': '75', 'lang': 'en'}, 'tUqUdu0Sjyc': {'id': 'tUqUdu0Sjyc', 'chnlid': 'UCTZRcDjjkVajGL6wd76UnGg', 'categ_id': 27, 'title': 'User Registration and Login Authentication | Django (3.0)  Crash Course Tutorials (pt 14)', 'view_count': '192502', 'likecount': '3294', 'dislikecount': '31', 'lang': 'en'}, 'iINE3iaN1Oo': {'id': 'iINE3iaN1Oo', 'chnlid': 'UCEXgQzMw_DXxk1M4Rlsciag', 'categ_id': 27, 'title': '5 HOURS COMPLETE DJANGO TUTORIAL - BUILD STOCK MANAGEMENT SYSTEM', 'view_count': '6966', 'likecount': '211', 'dislikecount': '1', 'lang': 'en-GB'}, 'e1IyzVyrLSU': {'id': 'e1IyzVyrLSU', 'chnlid': 'UC29ju8bIPH5as8OGnQzwJyA', 'categ_id': 28, 'title': 'Python Django Crash Course', 'view_count': '202728', 'likecount': '4615', 'dislikecount': '71', 'lang': 'en'}, '4RWFvXDUmjo': {'id': '4RWFvXDUmjo', 'chnlid': 'UCTZRcDjjkVajGL6wd76UnGg', 'categ_id': 27, 'title': 'To Do App | Django 3.0', 'view_count': '96989', 'likecount': '2158', 'dislikecount': '24', 'lang': 'en'}, 'YZvRrldjf1Y': {'id': 'YZvRrldjf1Y', 'chnlid': 'UC8butISFwT-Wl7EV0hUK0BQ', 'categ_id': 27, 'title': 'How to Build an E-commerce Website with Django and Python', 'view_count': '593708', 'likecount': '11034', 'dislikecount': '178', 'lang': 'en'}, 'WrZ10AZYbv4': {'id': 'WrZ10AZYbv4', 'chnlid': 'UC7dD1bOWXiJH3lJLsTInxOQ', 'categ_id': 27, 'title': 'Python Django Project \xf0\x9f\x94\xa5on Car Servicing System \xf0\x9f\x9a\x97.', 'view_count': '10174', 'likecount': '255', 'dislikecount': '16', 'lang': 'en-GB'}, 'f1R_bykXHGE': {'id': 'f1R_bykXHGE', 'chnlid': 'UCWEHue8kksIaktO8KTTN_zg', 'categ_id': 27, 'title': 'Create a Twitter-like App with Python Django JavaScript and React. Full TUTORIAL', 'view_count': '282174', 'likecount': '10798', 'dislikecount': '86', 'lang': 'en'}}"
from pprint import pprint

compdata = [{'4RWFvXDUmjo': {'categ_id': 27,
                             'chnlid': 'UCTZRcDjjkVajGL6wd76UnGg',
                             'dislikecount': '24',
                             'id': '4RWFvXDUmjo',
                             'lang': 'en',
                             'likecount': '2159',
                             'title': 'To Do App | Django 3.0',
                             'view_count': '96995'},
             'F5mRW0jo-U4': {'categ_id': 27,
                             'chnlid': 'UC8butISFwT-Wl7EV0hUK0BQ',
                             'dislikecount': '614',
                             'id': 'F5mRW0jo-U4',
                             'lang': 'en',
                             'likecount': '24911',
                             'title': 'Python Django Web Framework - Full Course for '
                                      'Beginners',
                             'view_count': '1796920'},
             'HRLIEgwYSHc': {'categ_id': 27,
                             'chnlid': 'UCkw4JCwteGrDHIsyIIKo4tQ',
                             'dislikecount': '75',
                             'id': 'HRLIEgwYSHc',
                             'lang': 'en',
                             'likecount': '2215',
                             'title': 'Python Django Tutorial | Learn Python Django In 3 '
                                      'Hours | Python Web Development | Edureka',
                             'view_count': '148880'},
             'JT80XhYJdBw': {'categ_id': 27,
                             'chnlid': 'UCqrILQNl5Ed9Dz6CGMyvMTQ',
                             'dislikecount': '704',
                             'id': 'JT80XhYJdBw',
                             'lang': 'en',
                             'likecount': '19565',
                             'title': 'Python Django Tutorial 2020 - Full Course for '
                                      'Beginners',
                             'view_count': '670381'},
             'OTmQOjsl0eg': {'categ_id': 28,
                             'chnlid': 'UC59K-uG2A5ogwIrHw4bmlEg',
                             'dislikecount': '373',
                             'id': 'OTmQOjsl0eg',
                             'lang': 'en',
                             'likecount': '13387',
                             'title': 'Django Tutorial for Beginners | Full Course',
                             'view_count': '873338'},
             'WrZ10AZYbv4': {'categ_id': 27,
                             'chnlid': 'UC7dD1bOWXiJH3lJLsTInxOQ',
                             'dislikecount': '16',
                             'id': 'WrZ10AZYbv4',
                             'lang': 'en-GB',
                             'likecount': '255',
                             'title': 'Python Django Project 🔥on Car Servicing System 🚗.',
                             'view_count': '10182'},
             'YZvRrldjf1Y': {'categ_id': 27,
                             'chnlid': 'UC8butISFwT-Wl7EV0hUK0BQ',
                             'dislikecount': '178',
                             'id': 'YZvRrldjf1Y',
                             'lang': 'en',
                             'likecount': '11034',
                             'title': 'How to Build an E-commerce Website with Django and '
                                      'Python',
                             'view_count': '593780'},
             'YfO28Ihehbk': {'categ_id': 28,
                             'chnlid': 'UC59K-uG2A5ogwIrHw4bmlEg',
                             'dislikecount': '184',
                             'id': 'YfO28Ihehbk',
                             'lang': 'en',
                             'likecount': '13068',
                             'title': 'Python Tutorial for Beginner | Full Course',
                             'view_count': '593751'},
             'e1IyzVyrLSU': {'categ_id': 28,
                             'chnlid': 'UC29ju8bIPH5as8OGnQzwJyA',
                             'dislikecount': '71',
                             'id': 'e1IyzVyrLSU',
                             'lang': 'en',
                             'likecount': '4615',
                             'title': 'Python Django Crash Course',
                             'view_count': '202753'},
             'f1R_bykXHGE': {'categ_id': 27,
                             'chnlid': 'UCWEHue8kksIaktO8KTTN_zg',
                             'dislikecount': '86',
                             'id': 'f1R_bykXHGE',
                             'lang': 'en',
                             'likecount': '10801',
                             'title': 'Create a Twitter-like App with Python Django '
                                      'JavaScript and React. Full TUTORIAL',
                             'view_count': '282212'},
             'iINE3iaN1Oo': {'categ_id': 27,
                             'chnlid': 'UCEXgQzMw_DXxk1M4Rlsciag',
                             'dislikecount': '1',
                             'id': 'iINE3iaN1Oo',
                             'lang': 'en-GB',
                             'likecount': '211',
                             'title': '5 HOURS COMPLETE DJANGO TUTORIAL - BUILD STOCK '
                                      'MANAGEMENT SYSTEM',
                             'view_count': '6973'},
             'size': 5,
             'skill': 'DJANGO',
             'tUqUdu0Sjyc': {'categ_id': 27,
                             'chnlid': 'UCTZRcDjjkVajGL6wd76UnGg',
                             'dislikecount': '31',
                             'id': 'tUqUdu0Sjyc',
                             'lang': 'en',
                             'likecount': '3294',
                             'title': 'User Registration and Login Authentication | '
                                      'Django (3.0)  Crash Course Tutorials (pt 14)',
                             'view_count': '192532'}}]
for i in compdata[0]:
    pprint(compdata[0][i])
